server {
    listen 8093 ssl http2;
    server_name lightdao.net;
    ssl_certificate /etc/letsencrypt/live/lightdao.net/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/lightdao.net/privkey.pem;
    root /var/www/lightdao_staging;
    location / { add_header Cache-Control "no-store" always; try_files $uri $uri/ /index.html; }
    location /js/ { add_header Cache-Control "no-store" always; try_files $uri =404; }
    location /css/ { add_header Cache-Control "immutable" always; try_files $uri =404; }
    location /gw/ { proxy_pass http://127.0.0.1:8080/; proxy_set_header Host $host; proxy_read_timeout 60s; }
    location /rpc/ { proxy_pass http://127.0.0.1:26657/; proxy_set_header Host $host; proxy_read_timeout 60s; }
}
